### ISSUE TITLE
Localización de Plataforma para Argentina

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#12]
Se definen aquí tareas, que describen necesidades puntuales y relevantes al contexto Argentina, para con el uso de la plataforma:

### Server/Web

+ [x] #13 Soporte para cargar CUIT en restaurants y tiendas
+ [x] #14 Configuración de moneda
+ [x] #15 Configuración de Impuestos
+ [x] #16 Configuración de números de teléfono (móviles) con formato de Argentina

> Más información sobre campos de formularios en #3 

### App Mobile

+ [x] #17 Traducciones al español

**Comment by sgobotta** [comment]
Se cierra #17
