### ISSUE TITLE
Implementar pasarela de pagos con Mercadopago

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#21]
Se definen aquí tareas, que describen necesidades puntuales y relevantes al contexto Argentina, para con el medio de pagos `Mercadopago`

### Server/Web

+ [x] #19 Implementar checkout básico utilizando Mercadopago
+ [x] #35 Implementar soporte para cambiar entre los modos `test` y `live`
+ [x] #36 MercadoPago como método de pago
+ [x] #20 Implementar soporte para pedido http de `preferences` de Mercadopago
+ [x] #22 Implementación de Split Payment

### App Mobile

+ [x] #10 Implementar checkout básico con Mercadopago en la app móvil
+ [x] #44 Implementar servicio de envío de identificación de pago al servidor

**Comment by maxi3390** [comment]
Linkeo #36

**Comment by sgobotta** [comment]
Cierro #20 y agrego #44
